local lootTest = TalkAction("/loottest")
local BATCH_SIZE = 1000
local activeTests = {}

local function getPercent(value)
    return (value / 100000) * 100
end

local function collectConfiguredLoot(lootList, configuredLoot, parentPath)
    for _, loot in ipairs(lootList) do
        local itemId = loot.itemId
        local chance = tonumber(loot.chance) or 0
        local path = parentPath and (parentPath .. " x " .. string.format("%.6f%%", getPercent(chance))) or string.format("%.6f%%", getPercent(chance))

        if itemId then
            configuredLoot[itemId] = configuredLoot[itemId] or {}
            table.insert(configuredLoot[itemId], path)
        end

        if loot.childLoot and #loot.childLoot > 0 then
            collectConfiguredLoot(loot.childLoot, configuredLoot, path)
        end
    end
end

local function collectCorpseLoot(corpse, results)
    -- Reading the created corpse captures stack merging and nested containers as a player sees them.
    local seenInCorpse = {}
    for _, item in ipairs(corpse:getItems(true)) do
        local itemId = item:getId()
        local count = item:getCount()
        local result = results[itemId]
        if not result then
            result = { corpses = 0, amount = 0 }
            results[itemId] = result
        end

        seenInCorpse[itemId] = true
        result.amount = result.amount + count
    end

    for itemId in pairs(seenInCorpse) do
        results[itemId].corpses = results[itemId].corpses + 1
    end
end

local function printResults(state)
    local rows = {}
    local included = {}
    for itemId, configured in pairs(state.configuredLoot) do
        local result = state.results[itemId] or { corpses = 0, amount = 0 }
        local itemType = ItemType(itemId)
        local name = itemType and itemType:getName() or ("item " .. itemId)
        table.insert(rows, {
            itemId = itemId,
            name = name,
            corpses = result.corpses,
            amount = result.amount,
            configured = configured,
        })
        included[itemId] = true
    end

    for itemId, result in pairs(state.results) do
        if not included[itemId] then
            local itemType = ItemType(itemId)
            local name = itemType and itemType:getName() or ("item " .. itemId)
            table.insert(rows, {
                itemId = itemId,
                name = name,
                corpses = result.corpses,
                amount = result.amount,
                configured = { "generated by container" },
            })
        end
    end

    table.sort(rows, function(a, b)
        return a.name < b.name
    end)

    print("")
    print("====== LOOT TEST (PRODUCTION PATH) ======")
    print("Monster: " .. state.monsterName)
    print("Simulations: " .. state.completed)
    print("rateLoot: " .. configManager.getNumber(configKeys.RATE_LOOT))
    print("Time: " .. string.format("%.2f", os.clock() - state.startedAt) .. "s")
    print("------------------------------------------")

    for _, row in ipairs(rows) do
        local seenPercent = (row.corpses / state.completed) * 100
        local averageAmount = row.amount / state.completed
        print(string.format(
            "%s [%d] | XML path: %s | seen: %.6f%% | corpses: %d | amount: %d | avg/kill: %.6f",
            row.name,
            row.itemId,
            table.concat(row.configured, " | "),
            seenPercent,
            row.corpses,
            row.amount,
            averageAmount
        ))
    end

    print("==========================================")
    print("")
end

local function runBatch(playerId)
    local state = activeTests[playerId]
    if not state then
        return
    end

    local batchEnd = math.min(state.completed + BATCH_SIZE, state.tries)
    for _ = state.completed + 1, batchEnd do
        local corpse = Game.createItem(state.corpseId)
        if not corpse then
            activeTests[playerId] = nil
            return
        end

        for _, loot in ipairs(state.loot) do
            corpse:createLootItem(loot)
        end

        collectCorpseLoot(corpse, state.results)
        corpse:remove()
    end

    state.completed = batchEnd
    if state.completed < state.tries then
        addEvent(runBatch, 1, playerId)
        return
    end

    printResults(state)
    activeTests[playerId] = nil

    local player = Player(playerId)
    if player then
        player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, "Loot test finalizado. Veja o console do servidor.")
    end
end

function lootTest.onSay(player, words, param)
    if not player:getGroup():getAccess() then
        player:sendCancelMessage("Comando restrito a membros da equipe.")
        return false
    end

    local monsterName, tries = param:match("^%s*(.-)%s*,%s*(%d+)%s*$")

    if not monsterName or monsterName == "" then
        player:sendCancelMessage("Use: /loottest rat, 1000000")
        return false
    end

    tries = tonumber(tries)

    if not tries or tries <= 0 then
        player:sendCancelMessage("Quantidade invalida.")
        return false
    end

    local monsterType = MonsterType(monsterName)

    if not monsterType then
        player:sendCancelMessage("Monstro nao encontrado: " .. monsterName)
        return false
    end

    local loot = monsterType:getLoot()
    local corpseId = monsterType:corpseId()

    if not loot or #loot == 0 then
        player:sendCancelMessage("Esse monstro nao tem loot.")
        return false
    end

    if corpseId == 0 then
        player:sendCancelMessage("Esse monstro nao possui corpse para simular o loot real.")
        return false
    end

    local playerId = player:getId()
    if activeTests[playerId] then
        player:sendCancelMessage("Ja existe um loot test em andamento para voce.")
        return false
    end

    local configuredLoot = {}
    collectConfiguredLoot(loot, configuredLoot)

    activeTests[playerId] = {
        monsterName = monsterType:name(),
        corpseId = corpseId,
        loot = loot,
        tries = tries,
        completed = 0,
        results = {},
        configuredLoot = configuredLoot,
        startedAt = os.clock(),
    }

    player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, "Loot test iniciado. O resultado sera enviado ao console do servidor.")
    addEvent(runBatch, 1, playerId)
    return false
end

lootTest:separator(" ")
lootTest:register()
